"use client"; // Ensure this is a client-side component
import { createTheme, ThemeProvider, CssBaseline } from "@mui/material";
import type { Metadata } from "next";
import localFont from "next/font/local";
import Navbar from "./_features/navbar/Navbar";
import Footer from "./_features/footer/Footer";

// Define your custom colors
const CRIMSON_RED = "#c1121f";

// Import fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Define the MUI theme with CRIMSON_RED as the primary color
const theme = createTheme({
  palette: {
    primary: {
      main: CRIMSON_RED,
    },
    secondary: {
      main: "#007bff", 
    },
  },
  typography: {
    fontFamily: ["var(--font-geist-sans)", "Arial", "sans-serif"].join(","),
  },
});

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider theme={theme}>
          <CssBaseline /> 
          <Navbar />
          <main className="main-wrapper">{children}</main>
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
